[package]
name = "learn_rust"
version = "0.1.0"
authors = ["kaih917 <kai_h_917@msn.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = "0.0.14"